= Micro SVG Document Structure
:toc:

== Elements

=== svg

The `svg` element is the root element of the document.
It's defined only once and can't be nested, unlike the SVG spec.

Children: `defs`, `g`, `path`, `text` and `image`.

=== defs

Children: `linearGradient`, `radialGradient`, `clipPath` and `pattern`.

[[linearGradient_elem]]

=== linearGradient

Gradient has all attributes resolved and at least two `stop` children.

`stop` children will always have unique, ordered `offset` values.

Gradient doesn't have `xlink:href` attribute because all attributes and `stop` children
are already resolved and copied to the gradient.

Attributes: `id`, `x1`, `y1`, `x2`, `y2`, `gradientUnits`, `spreadMethod`,
`gradientTransform`.

* `id` always set. Never empty.
* `gradientTransform` always a `matrix`. Never `translate`, `scale`, etc.
* `gradientTransform` with `matrix(1 0 0 1 0 0)` is skipped.

Children: `<<stop_elem,stop>>`

=== radialGradient

See `<<linearGradient_elem,linearGradient>>`.

Attributes: `id`, `cx`, `cy`, `r`, `fx`, `fy`, `gradientUnits`, `spreadMethod`,
`gradientTransform`.

* `id` always set. Never empty.
* `r` always > 0.
* `fx` and `fy` are always inside the circle defined by `cx`, `cy` and `r`.
* `gradientTransform` always a `matrix`. Never `translate`, `scale`, etc.
* `gradientTransform` with `matrix(1 0 0 1 0 0)` is skipped.

Children: `<<stop_elem,stop>>`

[[stop_elem]]

=== stop

Attributes: `offset`, `stop-color`, `stop-opacity`.

* `offset` and `stop-opacity` are always in 0..1 range.
* `stop-color` is always a valid #RRGGBB color.

=== pattern

Pattern defines a texture image that can be used by `fill` and `stroke`.

Children: `g`, `path`, `text` and `image`.

=== clipPath

`clipPath` defines a 1-bit mask using children elements.

Children: `path` and `text`.

=== g

The group element indicates that a new canvas should be created.
All groups children elements will be rendered on it and then merged to
the parent canvas.

Since it's pretty expensive, especially memory wise, _usvg_
will remove as many groups as possible.
All the remaining one will indicate that a new canvas must be created.

Children: `g`, `path`, `text` and `image`.

=== path

First, the _usvg_ preprocessor will convert all the shapes into paths.
Then it will simplify path's data so it will contain only absolute
MoveTo, LineTo, CurveTo and ClosePath segments.

The `path` element can have <<fill_attrs, filling>> and
<<stroke_attrs,stroking>> attributes.

=== text

The text is one of the most complex parts of the SVG.
_usvg_ will modify the input element and its children a lot.

The simplest `text` element like `<text>Text</text>` will be converted to:

```xml
<text>
  <tspan
     x="0"
     y="0">
    <tspan
       fill="#000000"
       font-family="Times New Roman"
       font-size="12"
       stroke="none">
      Text
    </tspan>
  </tspan>
</text>
```

In _usvg_, the `text` element is just a container for
https://www.w3.org/TR/SVG11/text.html#TextChunk[text chunks],
represented via `tspan`.
So all `text` elements will have a three-level structure:

* `text` - container
** `tspan` - text chunk
*** `tspan` - text container

The `text` itself can have only a `transform` attribute.

_Text chunk_ can have `x`, `y` and `text-anchor` attributes.

And the _text container_ can have <<fill_attrs, filling>>,
<<stroke_attrs,stroking>>, <<font_attrs,font>> and `text-decoration` attributes.

// TODO: explain text-decoration

=== image

An image can have base64 encoded data or a path to an image.

Attributes: `id`, `x`, `y`, `width`, `height`, `preserveAspectRatio`, `xlink:href`
and `transform`.

== Attributes

[[fill_attrs]]

=== Filling attributes

Filling attributes refers to:

- `fill`
- `fill-opacity`
- `fill-rule`

[[stroke_attrs]]

=== Stroking attributes

Stroking attributes refers to:

- `stroke`
- `stroke-dasharray`
- `stroke-dashoffset`
- `stroke-miterlimit`
- `stroke-opacity`
- `stroke-width`
- `stroke-linecap`
- `stroke-linejoin`

[[font_attrs]]

=== Font attributes

Font attributes refers to:

- `font-family`
- `font-size`
- `font-style`
- `font-variant`
- `font-weight`
- `font-stretch`
